query Fetch {
  queryMinhasimpressoesContents{
    id
    data:flatData{
      content
      title
      datapublicacao
      date
      images{
        url
      }
    }
  },
  queryViroufilmeContents{
    id
    data:flatData{
      title
      date
      datapublicacao
      content
      images{
        url
      }
    }
  },
  queryEmaltaContents{
    id
    data:flatData{
      content
      title
      datapublicacao
      date
      images{
        url
      }
    }
  },
  queryMontandoaestanteContents{
    id
    data:flatData{
      title
      date
      datapublicacao
      content
      images{
        url
      }
    }
  },
    queryDestaquesContents{
    id
    data:flatData{
      title
      date
      content
      datapublicacao
      images{
      	url
        slug
    	}
    }
  }

}
