query Fetch {
  queryMinhasimpressoesContents {
    id
    data: flatData {
      content
      title
      datapublicacao
      date
      images {
        url
      }
    }
  }
  queryViroufilmeContents {
    id
    data: flatData {
      title
      date
      datapublicacao
      content
      images {
        url
      }
    }
  }
  queryEmaltaContents {
    id
    data: flatData {
      content
      title
      datapublicacao
      date
      images {
        url
      }
    }
  }
  queryMontandoaestanteContents {
    id
    data: flatData {
      title
      date
      datapublicacao
      content
      images {
        url
      }
    }
  }
  queryDestaquesContents {
    id
    data: flatData {
      title
      date
      content
      datapublicacao
      images {
        url
        slug
      }
    }
  }
  querySaladearteContents {
    id
    data: flatData {
      description
      images {
        url
      }
    }
  }
  queryEventsContents {
    id
    data: flatData {
      title
      date
      description
      images {
        url
      }
    }
  }
  querySaladearteContents {
    id
    data: flatData {
      description
      images {
        url
      }
    }
  }
    queryDreamybdContents{
    id
    data:flatData{
      content
      title
      identificador
      datapublicacao
      description
      date
      images{
        url
      }
    }
  }
    queryImagendestaqueContents{
    id
    data: flatData{
      src {
        url
      }
    }
  }
}
