query Fetch
{
  queryMontandoaestanteContents{
   id
    createdByUser {
      id
      displayName
    }  
    created
    data:flatData{
      content
      title
      datapublicacao
      date
      images{
        url
      }
    }
  }
}